// Copyright 2014 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// @dart = 2.8

// AUTOGENERATED FILE DO NOT EDIT!
// This file was generated by vitool.
part of material_animated_icons;

const _AnimatedIconData _$add_close = _AnimatedIconData(
  Size(48.0, 48.0),
  <_PathFrames>[
    _PathFrames(
      opacities: <double>[
        1.0,
        1.0,
      ],
      commands: <_PathCommand>[
        _PathMoveTo(
          <Offset>[
            Offset(22, 8),
            Offset(11.27, 14.1),
          ],
        ),
        _PathLineTo(
          <Offset>[
            Offset(26, 8),
            Offset(14.1, 11.27),
          ],
        ),
        _PathLineTo(
          <Offset>[
            Offset(26, 22),
            Offset(24, 21.17),
          ],
        ),
        _PathLineTo(
          <Offset>[
            Offset(40, 22),
            Offset(33.9, 11.27),
          ],
        ),
        _PathLineTo(
          <Offset>[
            Offset(40, 26),
            Offset(36.73, 14.1),
          ],
        ),
        _PathLineTo(
          <Offset>[
            Offset(26, 26),
            Offset(26.83, 24),
          ],
        ),
        _PathLineTo(
          <Offset>[
            Offset(26, 40),
            Offset(36.73, 33.9),
          ],
        ),
        _PathLineTo(
          <Offset>[
            Offset(22, 40),
            Offset(33.9, 36.73),
          ],
        ),
        _PathLineTo(
          <Offset>[
            Offset(22, 26),
            Offset(24, 26.83),
          ],
        ),
        _PathLineTo(
          <Offset>[
            Offset(8, 26),
            Offset(14.1, 36.73),
          ],
        ),
        _PathLineTo(
          <Offset>[
            Offset(8, 22),
            Offset(11.27, 33.9),
          ],
        ),
        _PathLineTo(
          <Offset>[
            Offset(22, 22),
            Offset(21.17, 24),
          ],
        ),
        _PathClose(),
      ],
    ),
  ],
);
